In [24]:
import pandas as pd
import numpy as np
from IPython.display import Markdown as md

In [2]:
n = 100

In [3]:
df = pd.DataFrame({'Store': np.random.choice(['Store_1', 'Store_2'], n),
   'Product': np.random.choice(['Product_1',
   'Product_2'], n),
   'Revenue': (np.random.random(n) * 50 + 10).round(2),
   'Quantity': np.random.randint(1, 10, size=n)})

In [22]:
df.head(3)

     Store    Product  Revenue  Quantity
0  Store_1  Product_2    29.97         9
1  Store_2  Product_1    50.41         1
2  Store_1  Product_2    51.51         3

In [23]:
df.info

<bound method DataFrame.info of       Store    Product  Revenue  Quantity
0   Store_1  Product_2    29.97         9
1   Store_2  Product_1    50.41         1
2   Store_1  Product_2    51.51         3
3   Store_1  Product_1    13.44         3
4   Store_2  Product_2    31.72         6
5   Store_2  Product_2    30.68         7
6   Store_1  Product_1    57.91         3
7   Store_1  Product_2    56.34         4
8   Store_1  Product_1    40.66         8
9   Store_1  Product_1    22.52         6
10  Store_2  Product_2    17.47         6
11  Store_2  Product_2    51.35         5
12  Store_2  Product_2    22.92         5
13  Store_2  Product_2    46.37         1
14  Store_2  Product_2    42.24         7
15  Store_1  Product_1    50.76         7
16  Store_2  Product_1    18.45         7
17  Store_2  Product_2    54.04         8
18  Store_2  Product_2    14.40         9
19  Store_2  Product_2    36.62         2
20  Store_2  Product_1    14.80         2
21  Store_2  Product_2    51.32         1
22  Store_2  Product_1    29.23         2
23  Store_1  Product_1    43.57         2
24  Store_2  Product_2    18.54         5
25  Store_1  Product_2    43.46         2
26  Store_2  Product_1    16.23         6
27  Store_1  Product_1    26.46         9
28  Store_1  Product_1    58.48         1
29  Store_2  Product_1    15.39         4
..      ...        ...      ...       ...
70  Store_1  Product_2    34.01         9
71  Store_1  Product_1    24.40         5
72  Store_2  Product_2    52.77         8
73  Store_2  Product_2    27.43         1
74  Store_1  Product_2    45.10         6
75  Store_1  Product_2    22.06         9
76  Store_2  Product_2    16.48         4
77  Store_2  Product_1    12.08         3
78  Store_1  Product_1    54.74         7
79  Store_2  Product_1    34.90         5
80  Store_2  Product_1    15.31         3
81  Store_1  Product_2    59.95         7
82  Store_2  Product_2    34.93         2
83  Store_2  Product_1    24.20         7
84  Store_2  Product_2    39.35         2
85  Store_2  Product_1    24.70         4
86  Store_2  Product_2    59.79         2
87  Store_2  Product_2    21.89         5
88  Store_2  Product_1    16.10         2
89  Store_2  Product_2    23.59         7
90  Store_2  Product_1    51.24         8
91  Store_2  Product_2    11.32         2
92  Store_1  Product_1    26.69         3
93  Store_2  Product_1    33.09         9
94  Store_2  Product_2    10.85         7
95  Store_1  Product_2    36.60         9
96  Store_2  Product_1    33.59         7
97  Store_1  Product_1    39.69         4
98  Store_1  Product_1    58.89         4
99  Store_1  Product_1    31.38         6

[100 rows x 4 columns]>

In [5]:
df1 = df.groupby(['Store', 'Product']).pipe(lambda grp: grp.Revenue.sum())

In [6]:
type(df1)

pandas.core.series.Series

In [7]:
df1.index

MultiIndex(levels=[['Store_1', 'Store_2'], ['Product_1', 'Product_2']],
           codes=[[0, 0, 1, 1], [0, 1, 0, 1]],
           names=['Store', 'Product'])

In [8]:
df1

Store    Product
Store_1  Product_1     905.46
         Product_2     752.02
Store_2  Product_1     645.97
         Product_2    1090.10
Name: Revenue, dtype: float64

In [9]:
df2 = df1.reset_index()

In [10]:
df3 = df1.unstack()

In [11]:
df2

     Store    Product  Revenue
0  Store_1  Product_1   905.46
1  Store_1  Product_2   752.02
2  Store_2  Product_1   645.97
3  Store_2  Product_2  1090.10

In [12]:
type(df3)

pandas.core.frame.DataFrame

In [13]:
df3

Product  Product_1  Product_2
Store
Store_1     905.46     752.02
Store_2     645.97    1090.10

In [14]:
df3.columns

Index(['Product_1', 'Product_2'], dtype='object', name='Product')

In [15]:
df3.index

Index(['Store_1', 'Store_2'], dtype='object', name='Store')

In [16]:
df4 = df3.iloc[0]

In [17]:
type(df4)

pandas.core.series.Series

In [18]:
df4.index

Index(['Product_1', 'Product_2'], dtype='object', name='Product')

In [19]:
df4

Product
Product_1    905.46
Product_2    752.02
Name: Store_1, dtype: float64

In [21]:
df3.iloc[1]

Product
Product_1     645.97
Product_2    1090.10
Name: Store_2, dtype: float64

In [20]:
for name, group in df1:
    print(name)

TypeError: cannot unpack non-iterable float object

In [16]:
(df.groupby(['Store', 'Product'])
   .pipe(lambda grp: grp.Revenue.sum() / grp.Quantity.sum())
   .unstack().round(2))

Product  Product_1  Product_2
Store
Store_1       7.27       5.81
Store_2       5.59       7.73

### Get the data set from https://www.kaggle.com/currie32/crimes-in-chicago

In [26]:
data = pd.read_csv("chicago_crime_data.csv")

In [28]:
data.shape

(265382, 22)

In [40]:
md("### The data frame has %i Records and %i Columns"%(data.shape[0], data.shape[1]))

### The data frame has 265382 Records and 22 Columns

In [41]:
data.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [42]:
data.head(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,24392,JB323792,06/26/2018 05:16:00 PM,077XX S COLES AVE,0110,HOMICIDE,FIRST DEGREE MURDER,YARD,False,False,...,7.0,43.0,01A,NaN,NaN,2018,02/01/2019 04:19:40 PM,NaN,NaN,NaN
1,11582357,JC136122,12/26/2018 08:00:00 AM,008XX N CHRISTIANA AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,...,27.0,23.0,11,NaN,NaN,2018,02/01/2019 04:19:40 PM,NaN,NaN,NaN
2,11582352,JC136052,12/01/2018 12:00:00 AM,030XX S KARLOV AVE,5000,OTHER OFFENSE,OTHER CRIME AGAINST PERSON,APARTMENT,False,False,...,22.0,30.0,26,NaN,NaN,2018,02/01/2019 04:19:40 PM,NaN,NaN,NaN

In [44]:
data.tail(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
265379,23758,JB100522,01/01/2018 11:33:00 AM,026XX N HAMPDEN CT,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,43.0,7.0,01A,1172664.0,1917743.0,2018,01/08/2018 03:55:29 PM,41.929727,-87.640921,"(41.929726567, -87.64092074)"
265380,23757,JB100159,01/01/2018 02:46:00 AM,039XX W CORNELIA AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,...,30.0,21.0,01A,1149289.0,1922972.0,2018,01/08/2018 03:55:29 PM,41.944561,-87.726682,"(41.944561251, -87.726681812)"
265381,11193631,JB102174,01/02/2018 12:30:00 PM,0000X N LA SALLE ST,0870,THEFT,POCKET-PICKING,RESTAURANT,False,False,...,42.0,32.0,06,NaN,NaN,2018,01/09/2018 03:50:53 PM,NaN,NaN,NaN

In [46]:
data.info() #Summary of the Data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265382 entries, 0 to 265381
Data columns (total 22 columns):
ID                      265382 non-null int64
Case Number             265382 non-null object
Date                    265382 non-null object
Block                   265382 non-null object
IUCR                    265382 non-null object
Primary Type            265382 non-null object
Description             265382 non-null object
Location Description    264637 non-null object
Arrest                  265382 non-null bool
Domestic                265382 non-null bool
Beat                    265382 non-null int64
District                265382 non-null int64
Ward                    265379 non-null float64
Community Area          265380 non-null float64
FBI Code                265382 non-null object
X Coordinate            263653 non-null float64
Y Coordinate            263653 non-null float64
Year                    265382 non-null int64
Updated On              265382 non-null object
Latitude                263653 non-null float64
Longitude               263653 non-null float64
Location                263653 non-null object
dtypes: bool(2), float64(6), int64(4), object(10)
memory usage: 41.0+ MB

In [52]:
data["FBI Code"].unique()

array(['01A', '11', '26', '06', '10', '05', '03', '14', '02', '17', '20',
       '08B', '04B', '07', '04A', '08A', '24', '15', '16', '18', '09',
       '01B', '12', '22', '13', '19'], dtype=object)

In [54]:
md("### The data frame has in total %i FBI Codes "%(len(data["FBI Code"].unique())))

### The data frame has in total 26 FBI Codes

In [56]:
data['Date'] = pd.to_datetime(data['Date'] )

In [57]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265382 entries, 0 to 265381
Data columns (total 22 columns):
ID                      265382 non-null int64
Case Number             265382 non-null object
Date                    265382 non-null datetime64[ns]
Block                   265382 non-null object
IUCR                    265382 non-null object
Primary Type            265382 non-null object
Description             265382 non-null object
Location Description    264637 non-null object
Arrest                  265382 non-null bool
Domestic                265382 non-null bool
Beat                    265382 non-null int64
District                265382 non-null int64
Ward                    265379 non-null float64
Community Area          265380 non-null float64
FBI Code                265382 non-null object
X Coordinate            263653 non-null float64
Y Coordinate            263653 non-null float64
Year                    265382 non-null int64
Updated On              265382 non-null object
Latitude                263653 non-null float64
Longitude               263653 non-null float64
Location                263653 non-null object
dtypes: bool(2), datetime64[ns](1), float64(6), int64(4), object(9)
memory usage: 41.0+ MB

### min(), max(), sum(), mean(), median(), mode(), can be applied for column values

In [59]:
data['Latitude'].min()

41.644589713

In [60]:
data['Latitude'].max()

42.022671246

In [73]:
data.isna().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description     745
Arrest                     0
Domestic                   0
Beat                       0
District                   0
Ward                       3
Community Area             2
FBI Code                   0
X Coordinate            1729
Y Coordinate            1729
Year                       0
Updated On                 0
Latitude                1729
Longitude               1729
Location                1729
dtype: int64

In [64]:
type(data.isna().sum())

pandas.core.series.Series

In [65]:
data.isna().sum().axes

[Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
        'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
        'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
        'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
        'Location'],
       dtype='object')]

### Fill null values for Ward with the current average

In [75]:
ward_mean = data['Ward'].mean()

In [76]:
ward_mean

23.439450747798432

In [77]:
data['Ward'] = data['Ward'].fillna(value = ward_mean)

In [78]:
data.isna().sum()

ID                         0
Case Number                0
Date                       0
Block                      0
IUCR                       0
Primary Type               0
Description                0
Location Description     745
Arrest                     0
Domestic                   0
Beat                       0
District                   0
Ward                       0
Community Area             2
FBI Code                   0
X Coordinate            1729
Y Coordinate            1729
Year                       0
Updated On                 0
Latitude                1729
Longitude               1729
Location                1729
dtype: int64

### Delete the rows with na values

In [79]:
data.dropna(axis=0, inplace=True)

In [80]:
data.isna().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [82]:
data.head(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
6,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,7.0,43.0,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.574960,"(41.761893792, -87.574959656)"
7,11492004,JB495913,2018-10-29 13:00:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)"
8,11488952,JB491843,2018-10-27 02:00:00,070XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,STREET,False,False,...,5.0,43.0,06,1190765.0,1858575.0,2018,01/30/2019 04:08:28 PM,41.766947,-87.576322,"(41.766946791, -87.57632241)"

In [83]:
### Delete in the rows do not reset the index

In [94]:
data.reset_index(inplace = True, drop=True)

In [95]:
data.head(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,7.0,43.0,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.574960,"(41.761893792, -87.574959656)"
1,11492004,JB495913,2018-10-29 13:00:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)"
2,11488952,JB491843,2018-10-27 02:00:00,070XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,STREET,False,False,...,5.0,43.0,06,1190765.0,1858575.0,2018,01/30/2019 04:08:28 PM,41.766947,-87.576322,"(41.766946791, -87.57632241)"

In [100]:
data.iloc[[0]]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,7.0,43.0,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.57496,"(41.761893792, -87.574959656)"

In [101]:
data.iloc[3:6]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
3,11488097,JB490633,2018-10-24 06:00:00,063XX S DORCHESTER AVE,0820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,...,20.0,42.0,06,1186589.0,1863270.0,2018,01/30/2019 04:08:28 PM,41.779930,-87.591480,"(41.779930114, -87.591480454)"
4,11481439,JB482043,2018-10-18 16:00:00,069XX S CRANDON AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,...,5.0,43.0,06,1192521.0,1859491.0,2018,01/30/2019 04:08:28 PM,41.769418,-87.569856,"(41.769417774, -87.569856281)"
5,11480921,JB481242,2018-10-18 20:30:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)"

In [109]:
data[['Date', 'Block']].iloc[[5]]

                 Date                Block
5 2018-10-18 20:30:00  065XX S KIMBARK AVE

In [108]:
data[['Date', 'Block']][5:6]

                 Date                Block
5 2018-10-18 20:30:00  065XX S KIMBARK AVE

In [110]:
data.iloc[4:8,2:4]

                 Date                 Block
4 2018-10-18 16:00:00   069XX S CRANDON AVE
5 2018-10-18 20:30:00   065XX S KIMBARK AVE
6 2018-10-16 21:30:00  061XX S WOODLAWN AVE
7 2018-10-14 05:00:00  071XX S JEFFERY BLVD

In [112]:
data.iloc[4:8,-1]

4    (41.769417774, -87.569856281)
5    (41.776382364, -87.594556922)
6    (41.783709683, -87.596276769)
7     (41.76587359, -87.576294705)
Name: Location, dtype: object

In [119]:
a = (data.Ward < 30)

In [121]:
type(a)

pandas.core.series.Series

In [130]:
a

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8          True
9          True
10         True
11         True
12         True
13        False
14         True
15         True
16         True
17         True
18         True
19         True
20         True
21        False
22        False
23         True
24         True
25         True
26         True
27         True
28         True
29        False
          ...
262982     True
262983     True
262984    False
262985     True
262986     True
262987     True
262988    False
262989     True
262990     True
262991    False
262992     True
262993    False
262994     True
262995     True
262996    False
262997     True
262998    False
262999    False
263000     True
263001    False
263002    False
263003     True
263004     True
263005     True
263006     True
263007     True
263008     True
263009     True
263010    False
263011    False
Name: Ward, Length: 263012, dtype: bool

In [142]:
s1 = pd.Series([False] * 263012, index=range(0, 263012))

In [145]:
s1.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [148]:
data.loc[a]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,7.0,43.0,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.574960,"(41.761893792, -87.574959656)"
1,11492004,JB495913,2018-10-29 13:00:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)"
2,11488952,JB491843,2018-10-27 02:00:00,070XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,STREET,False,False,...,5.0,43.0,06,1190765.0,1858575.0,2018,01/30/2019 04:08:28 PM,41.766947,-87.576322,"(41.766946791, -87.57632241)"
3,11488097,JB490633,2018-10-24 06:00:00,063XX S DORCHESTER AVE,0820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,...,20.0,42.0,06,1186589.0,1863270.0,2018,01/30/2019 04:08:28 PM,41.779930,-87.591480,"(41.779930114, -87.591480454)"
4,11481439,JB482043,2018-10-18 16:00:00,069XX S CRANDON AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,...,5.0,43.0,06,1192521.0,1859491.0,2018,01/30/2019 04:08:28 PM,41.769418,-87.569856,"(41.769417774, -87.569856281)"
5,11480921,JB481242,2018-10-18 20:30:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)"
6,11478932,JB478700,2018-10-16 21:30:00,061XX S WOODLAWN AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185269.0,1864636.0,2018,01/30/2019 04:08:28 PM,41.783710,-87.596277,"(41.783709683, -87.596276769)"
7,11476211,JB475196,2018-10-14 05:00:00,071XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,SIDEWALK,False,True,...,5.0,43.0,06,1190776.0,1858184.0,2018,01/30/2019 04:08:28 PM,41.765874,-87.576295,"(41.76587359, -87.576294705)"
8,11473764,JB471936,2018-10-06 01:00:00,072XX S SOUTH SHORE DR,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,...,7.0,43.0,06,1194918.0,1857750.0,2018,01/30/2019 04:08:28 PM,41.764582,-87.561127,"(41.764581624, -87.561127448)"
9,11469473,JB466082,2018-10-02 22:00:00,073XX S PHILLIPS AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,...,7.0,43.0,06,1193921.0,1856701.0,2018,01/30/2019 04:08:28 PM,41.761728,-87.564816,"(41.761727593, -87.564815996)"
10,11465469,JB460756,2018-10-03 01:00:00,063XX S MINERVA AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,20.0,42.0,06,1185274.0,1862873.0,2018,01/30/2019 04:08:28 PM,41.778872,-87.596314,"(41.778871742, -87.59631384)"
11,11464178,JB459003,2018-10-01 14:30:00,072XX S COLES AVE,0820,THEFT,$500 AND UNDER,RESIDENTIAL YARD (FRONT/BACK),False,False,...,7.0,43.0,06,1194392.0,1857739.0,2018,01/30/2019 04:08:28 PM,41.764564,-87.563056,"(41.764564381, -87.5630557)"
12,11449552,JB440022,2018-09-10 19:45:00,007XX N LA SALLE DR,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,CURRENCY EXCHANGE,False,False,...,2.0,8.0,10,1175000.0,1905549.0,2018,01/30/2019 04:08:28 PM,41.896214,-87.632703,"(41.896213602, -87.632702709)"
14,11407268,JB384464,2018-01-12 03:54:00,001XX N WESTERN AVE,1110,DECEPTIVE PRACTICE,BOGUS CHECK,CURRENCY EXCHANGE,False,False,...,27.0,28.0,11,1160382.0,1901043.0,2018,01/30/2019 04:08:28 PM,41.884164,-87.686516,"(41.884163773, -87.686516386)"
15,11386538,JB357833,2018-07-13 20:44:00,001XX N WESTERN AVE,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,CURRENCY EXCHANGE,False,False,...,27.0,28.0,10,1160382.0,1901043.0,2018,01/30/2019 04:08:28 PM,41.884164,-87.686516,"(41.884163773, -87.686516386)"
16,11376919,JB345407,2018-06-29 22:44:00,001XX N WESTERN AVE,1121,DECEPTIVE PRACTICE,COUNTERFEITING DOCUMENT,CURRENCY EXCHANGE,False,False,...,27.0,28.0,10,1160382.0,1901043.0,2018,01/30/2019 04:08:28 PM,41.884164,-87.686516,"(41.884163773, -87.686516386)"
17,11346714,JB305536,2018-06-11 12:30:00,045XX S LAVERGNE AVE,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,True,False,...,22.0,56.0,05,1143787.0,1874118.0,2018,01/30/2019 04:08:28 PM,41.810605,-87.748129,"(41.810604926, -87.748129424)"
18,11333200,JB287452,2018-05-31 20:35:00,007XX S WASHTENAW AVE,0340,ROBBERY,ATTEMPT: STRONGARM-NO WEAPON,STREET,False,False,...,28.0,27.0,03,1158477.0,1896843.0,2018,01/30/2019 04:08:28 PM,41.872678,-87.693627,"(41.872677761, -87.693626729)"
19,11560167,JC103552,2018-12-29 19:00:00,055XX S CALIFORNIA AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,16.0,63.0,08B,1158653.0,1867779.0,2018,01/29/2019 04:12:06 PM,41.792919,-87.693775,"(41.792919144, -87.693775007)"
20,11548779,JB569760,2018-12-28 05:05:00,083XX S PAULINA ST,0291,CRIM SEXUAL ASSAULT,ATTEMPT NON-AGGRAVATED,ALLEY,False,False,...,21.0,71.0,02,1166461.0,1849442.0,2018,01/29/2019 04:12:06 PM,41.742437,-87.665666,"(41.742437013, -87.665665849)"
23,11541363,JB560864,2018-12-20 10:37:00,051XX W 47TH ST,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,STREET,True,False,...,22.0,56.0,03,1142662.0,1872980.0,2018,01/29/2019 04:12:06 PM,41.807503,-87.752284,"(41.807503022, -87.752284096)"
24,11536723,JB555098,2018-12-15 21:15:00,020XX S MICHIGAN AVE,0496,BATTERY,AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST,RESIDENCE,True,True,...,3.0,33.0,04B,1177528.0,1890620.0,2018,01/29/2019 04:12:06 PM,41.855191,-87.623871,"(41.855190551, -87.623871195)"
25,11534484,JB552117,2018-12-13 08:00:00,021XX S HOYNE AVE,0460,BATTERY,SIMPLE,STREET,True,False,...,25.0,31.0,08B,1162704.0,1889642.0,2018,01/29/2019 04:12:06 PM,41.852830,-87.678309,"(41.852830043, -87.6783092)"
26,11532394,JB549386,2018-12-11 12:30:00,016XX N SAWYER AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,True,False,...,26.0,23.0,07,1154335.0,1910730.0,2018,01/29/2019 04:12:06 PM,41.910869,-87.708463,"(41.910868734, -87.708462658)"
27,11532264,JB549186,2018-12-11 17:30:00,019XX S CENTRAL PARK AVE,0320,ROBBERY,STRONGARM - NO WEAPON,CTA TRAIN,False,False,...,24.0,29.0,03,1152688.0,1889938.0,2018,01/29/2019 04:12:06 PM,41.853846,-87.715063,"(41.85384608, -87.715063469)"
28,11530142,JB546327,2018-10-18 11:00:00,055XX W WASHINGTON BLVD,0890,THEFT,FROM BUILDING,OTHER,True,False,...,29.0,25.0,06,1139376.0,1900200.0,2018,01/29/2019 04:12:06 PM,41.882259,-87.763674,"(41.882259032, -87.763674222)"
31,11497756,JB503467,2018-11-04 17:45:00,001XX N OAKLEY BLVD,031A,ROBBERY,ARMED: HANDGUN,ALLEY,True,False,...,27.0,28.0,03,1161062.0,1900805.0,2018,01/29/2019 04:12:06 PM,41.883497,-87.684026,"(41.883496589, -87.68402596)"
32,11493960,JB498187,2018-10-31 19:11:00,079XX S INGLESIDE AVE,051A,ASSAULT,AGGRAVATED: HANDGUN,RESIDENCE PORCH/HALLWAY,True,False,...,8.0,44.0,04A,1183941.0,1852514.0,2018,01/29/2019 04:12:06 PM,41.750477,-87.601524,"(41.750476891, -87.601523766)"
33,11482621,JB483682,2018-07-29 09:27:00,072XX S MARSHFIELD AVE,3960,INTIMIDATION,INTIMIDATION,RESIDENCE,False,False,...,17.0,67.0,26,1166596.0,1856670.0,2018,01/29/2019 04:12:06 PM,41.762269,-87.664965,"(41.762268782, -87.664965474)"
34,11480451,JB480643,2018-10-03 15:10:00,082XX S COTTAGE GROVE AVE,1110,DECEPTIVE PRACTICE,BOGUS CHECK,CURRENCY EXCHANGE,True,False,...,8.0,44.0,11,1182995.0,1850437.0,2018,01/29/2019 04:12:06 PM,41.744799,-87.605055,"(41.744799407, -87.60505473)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262970,23821,JB147904,2018-02-11 18:16:00,025XX W 63RD ST,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,False,False,...,15.0,66.0,01A,1160665.0,1862801.0,2018,02/18/2018 03:47:38 PM,41.779218,-87.686535,"(41.779217525, -87.68653451)"
262971,23820,JB148176,2018-02-11 13:03:00,073XX S BELL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,18.0,66.0,01A,1162674.0,1855992.0,2018,02/18/2018 03:47:38 PM,41.760491,-87.679359,"(41.760490977, -87.679359084)"
262972,23819,JB147538,2018-02-10 17:34:00,015XX N WESTERN AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,1.0,24.0,01A,1160132.0,1910080.0,2018,02/17/2018 03:55:23 PM,41.908967,-87.687184,"(41.90896722, -87.687184491)"
262973,23818,JB146880,2018-02-09 22:32:00,081XX S DREXEL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,8.0,44.0,01A,1183652.0,1851146.0,2018,02/16/2018 03:53:11 PM,41.746730,-87.602625,"(41.746729695, -87.602625355)"
262974,23815,JB145915,2018-02-08 20:43:00,006XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,False,False,...,28.0,25.0,01A,1141583.0,1903680.0,2018,02/15/2018 03:50:23 PM,41.891768,-87.755484,"(41.891768093, -87.755483944)"
262975,23814,JB143932,2018-02-07 09:23:00,014XX S KENNETH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,24.0,29.0,01A,1146951.0,1892767.0,2018,02/14/2018 03:52:17 PM,41.861721,-87.736048,"(41.861720639, -87.736048391)"
262976,23813,JB143932,2018-02-07 09:23:00,014XX S KENNETH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,24.0,29.0,01A,1146951.0,1892767.0,2018,02/14/2018 03:52:17 PM,41.861721,-87.736048,"(41.861720639, -87.736048391)"
262977,23812,JB142661,2018-02-06 04:10:00,062XX S MAY ST,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,False,False,...,16.0,68.0,01A,1169720.0,1863456.0,2018,02/13/2018 03:58:53 PM,41.780823,-87.653319,"(41.78082323, -87.653318937)"
262978,23811,JB141441,2018-02-05 01:10:00,118XX S INDIANA AVE,0110,HOMICIDE,FIRST DEGREE MURDER,VACANT LOT,False,False,...,9.0,53.0,01A,1179707.0,1826280.0,2018,02/12/2018 03:49:14 PM,41.678585,-87.617838,"(41.678585145, -87.617837834)"
262980,23809,JB140367,2018-02-03 21:03:00,024XX W 63RD ST,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,15.0,66.0,01A,1160989.0,1862809.0,2018,02/10/2018 04:08:39 PM,41.779233,-87.685346,"(41.779232785, -87.685346466)"
262981,23807,JB139392,2018-02-03 04:22:00,001XX E 119TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,9.0,53.0,01A,1179224.0,1825756.0,2018,02/10/2018 04:08:39 PM,41.677158,-87.619622,"(41.677158203, -87.619621673)"
262982,23806,JB138832,2018-02-03 05:21:00,004XX S PULASKI RD,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,24.0,26.0,01A,1149796.0,1897641.0,2018,02/10/2018 04:08:39 PM,41.875041,-87.725478,"(41.875040676, -87.725478099)"
262983,23805,JB139300,2018-02-02 21:51:00,086XX S CARPENTER ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,21.0,71.0,01A,1170825.0,1847590.0,2018,02/09/2018 04:07:13 PM,41.737261,-87.649730,"(41.737260844, -87.649730029)"
262985,23801,JB137001,2018-01-31 23:22:00,047XX W ARTHINGTON ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,24.0,25.0,01A,1144911.0,1895611.0,2018,02/07/2018 03:51:52 PM,41.869564,-87.743465,"(41.869563638, -87.743465231)"
262986,23800,JB137001,2018-01-31 23:22:00,047XX W ARTHINGTON ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,24.0,25.0,01A,1144911.0,1895611.0,2018,02/07/2018 03:51:52 PM,41.869564,-87.743465,"(41.869563638, -87.743465231)"
262987,23782,JB123082,2018-01-20 13:53:00,000XX W 69TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,CTA PROPERTY,True,False,...,6.0,69.0,01A,1177279.0,1859276.0,2018,02/04/2018 03:51:29 PM,41.769185,-87.625732,"(41.769185486, -87.625732415)"
262989,23796,JB131208,2018-01-27 02:27:00,025XX W DIVISION ST,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,...,26.0,24.0,01A,1159077.0,1907889.0,2018,02/03/2018 03:54:12 PM,41.902977,-87.691120,"(41.902976682, -87.691120334)"
262990,23793,JB130123,2018-01-26 10:32:00,070XX S VINCENNES AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,6.0,69.0,01A,1176892.0,1858475.0,2018,02/02/2018 03:49:15 PM,41.766996,-87.627175,"(41.766996182, -87.627175072)"
262992,23791,JB127534,2018-01-24 06:45:00,004XX S PULASKI RD,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,24.0,26.0,01A,1149797.0,1897611.0,2018,01/31/2018 03:55:34 PM,41.874958,-87.725475,"(41.874958334, -87.725475207)"
262994,23788,JB125943,2018-01-22 22:00:00,026XX E 83RD ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,7.0,46.0,01A,1195113.0,1850446.0,2018,01/29/2018 03:56:21 PM,41.744534,-87.560653,"(41.744534088, -87.560653171)"
262995,23786,JB124819,2018-01-22 02:45:00,058XX S SPRINGFIELD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,...,13.0,62.0,01A,1151376.0,1865388.0,2018,01/29/2018 03:56:21 PM,41.786503,-87.720522,"(41.786503336, -87.720521696)"
262997,23780,JB122301,2018-01-20 00:04:00,029XX E 79TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,7.0,43.0,01A,1196965.0,1853146.0,2018,01/27/2018 03:53:35 PM,41.751897,-87.553778,"(41.751897254, -87.553777728)"
263000,23773,JB111912,2018-01-11 05:51:00,049XX S CICERO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,GAS STATION,True,False,...,23.0,56.0,01A,1145196.0,1871375.0,2018,01/18/2018 03:58:25 PM,41.803051,-87.743030,"(41.803051264, -87.743030382)"
263003,23771,JB109877,2018-01-10 03:03:00,133XX S CALUMET AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,9.0,54.0,01A,1180829.0,1816902.0,2018,01/17/2018 03:56:34 PM,41.652825,-87.614017,"(41.652824848, -87.614017425)"
263004,23772,JB110393,2018-01-09 20:36:00,051XX W ADAMS ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,28.0,25.0,01A,1142053.0,1898843.0,2018,01/16/2018 04:04:00 PM,41.878486,-87.753878,"(41.878486072, -87.753877774)"
263005,23768,JB109411,2018-01-09 04:08:00,015XX W GARFIELD BLVD,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,False,False,...,16.0,67.0,01A,1166851.0,1868115.0,2018,01/16/2018 04:04:00 PM,41.793670,-87.663704,"(41.793669876, -87.66370422)"
263006,23767,JB107731,2018-01-07 16:37:00,007XX N CHRISTIANA AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,27.0,23.0,01A,1153907.0,1904830.0,2018,01/14/2018 03:51:28 PM,41.894687,-87.710192,"(41.894687135, -87.710192429)"
263007,23762,JB105277,2018-01-06 12:54:00,015XX E 62ND ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,5.0,42.0,01A,1187318.0,1864355.0,2018,01/13/2018 03:51:44 PM,41.782890,-87.588773,"(41.782890153, -87.588773433)"
263008,23763,JB105765,2018-01-05 18:50:00,053XX W LAKE ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,28.0,25.0,01A,1140721.0,1902054.0,2018,01/12/2018 03:58:33 PM,41.887322,-87.758690,"(41.887322035, -87.758689717)"
263009,23759,JB100839,2018-01-01 18:27:00,047XX S PRINCETON AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,...,3.0,37.0,01A,1175089.0,1873464.0,2018,01/08/2018 03:55:29 PM,41.808168,-87.633336,"(41.808168003, -87.633336457)"

In [160]:
data_arrest = (data.loc[(data['Arrest'] == True)])

In [162]:
data_arrest.reset_index(drop=True, inplace=True)

In [163]:
data_arrest

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11346714,JB305536,2018-06-11 12:30:00,045XX S LAVERGNE AVE,0610,BURGLARY,FORCIBLE ENTRY,RESIDENCE-GARAGE,True,False,...,22.0,56.0,05,1143787.0,1874118.0,2018,01/30/2019 04:08:28 PM,41.810605,-87.748129,"(41.810604926, -87.748129424)"
1,11560167,JC103552,2018-12-29 19:00:00,055XX S CALIFORNIA AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,16.0,63.0,08B,1158653.0,1867779.0,2018,01/29/2019 04:12:06 PM,41.792919,-87.693775,"(41.792919144, -87.693775007)"
2,11546276,JB566896,2018-12-25 11:30:00,038XX N DRAKE AVE,5004,SEX OFFENSE,ATT CRIM SEXUAL ABUSE,APARTMENT,True,False,...,35.0,16.0,17,1152038.0,1925399.0,2018,01/29/2019 04:12:06 PM,41.951167,-87.716513,"(41.951167285, -87.716513381)"
3,11542091,JB561201,2018-12-12 20:42:00,100XX W OHARE ST,1206,DECEPTIVE PRACTICE,"THEFT BY LESSEE,MOTOR VEH",AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA,True,False,...,41.0,76.0,11,1100658.0,1934241.0,2018,01/29/2019 04:12:06 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
4,11541363,JB560864,2018-12-20 10:37:00,051XX W 47TH ST,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,STREET,True,False,...,22.0,56.0,03,1142662.0,1872980.0,2018,01/29/2019 04:12:06 PM,41.807503,-87.752284,"(41.807503022, -87.752284096)"
5,11536723,JB555098,2018-12-15 21:15:00,020XX S MICHIGAN AVE,0496,BATTERY,AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST,RESIDENCE,True,True,...,3.0,33.0,04B,1177528.0,1890620.0,2018,01/29/2019 04:12:06 PM,41.855191,-87.623871,"(41.855190551, -87.623871195)"
6,11534484,JB552117,2018-12-13 08:00:00,021XX S HOYNE AVE,0460,BATTERY,SIMPLE,STREET,True,False,...,25.0,31.0,08B,1162704.0,1889642.0,2018,01/29/2019 04:12:06 PM,41.852830,-87.678309,"(41.852830043, -87.6783092)"
7,11532394,JB549386,2018-12-11 12:30:00,016XX N SAWYER AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,True,False,...,26.0,23.0,07,1154335.0,1910730.0,2018,01/29/2019 04:12:06 PM,41.910869,-87.708463,"(41.910868734, -87.708462658)"
8,11530142,JB546327,2018-10-18 11:00:00,055XX W WASHINGTON BLVD,0890,THEFT,FROM BUILDING,OTHER,True,False,...,29.0,25.0,06,1139376.0,1900200.0,2018,01/29/2019 04:12:06 PM,41.882259,-87.763674,"(41.882259032, -87.763674222)"
9,11525869,JB540499,2018-12-04 20:54:00,042XX N DRAKE AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,...,35.0,16.0,08B,1151966.0,1927859.0,2018,01/29/2019 04:12:06 PM,41.957919,-87.716713,"(41.957919121, -87.716712986)"
10,11497756,JB503467,2018-11-04 17:45:00,001XX N OAKLEY BLVD,031A,ROBBERY,ARMED: HANDGUN,ALLEY,True,False,...,27.0,28.0,03,1161062.0,1900805.0,2018,01/29/2019 04:12:06 PM,41.883497,-87.684026,"(41.883496589, -87.68402596)"
11,11493960,JB498187,2018-10-31 19:11:00,079XX S INGLESIDE AVE,051A,ASSAULT,AGGRAVATED: HANDGUN,RESIDENCE PORCH/HALLWAY,True,False,...,8.0,44.0,04A,1183941.0,1852514.0,2018,01/29/2019 04:12:06 PM,41.750477,-87.601524,"(41.750476891, -87.601523766)"
12,11480451,JB480643,2018-10-03 15:10:00,082XX S COTTAGE GROVE AVE,1110,DECEPTIVE PRACTICE,BOGUS CHECK,CURRENCY EXCHANGE,True,False,...,8.0,44.0,11,1182995.0,1850437.0,2018,01/29/2019 04:12:06 PM,41.744799,-87.605055,"(41.744799407, -87.60505473)"
13,11471939,JB469337,2018-10-09 21:08:00,024XX W LELAND AVE,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,True,False,...,47.0,4.0,03,1159100.0,1931137.0,2018,01/29/2019 04:12:06 PM,41.966770,-87.690395,"(41.96677027, -87.690395443)"
14,11470046,JB466774,2018-10-08 05:40:00,011XX S JEFFERSON ST,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,GAS STATION,True,False,...,25.0,28.0,03,1172488.0,1895410.0,2018,01/29/2019 04:12:06 PM,41.868447,-87.642229,"(41.868447451, -87.642228591)"
15,11386131,JB357097,2018-07-19 17:00:00,095XX S UNIVERSITY AVE,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,True,False,...,8.0,50.0,03,1185545.0,1841945.0,2018,01/29/2019 04:12:06 PM,41.721437,-87.595978,"(41.721436835, -87.595977853)"
16,11376786,JB345306,2018-06-20 19:25:00,001XX N WESTERN AVE,1122,DECEPTIVE PRACTICE,COUNTERFEIT CHECK,CURRENCY EXCHANGE,True,False,...,27.0,28.0,10,1160382.0,1901043.0,2018,01/29/2019 04:12:06 PM,41.884164,-87.686516,"(41.884163773, -87.686516386)"
17,11540979,JB560418,2018-12-19 21:23:00,073XX N ROGERS AVE,0479,BATTERY,AGG: HANDS/FIST/FEET SERIOUS INJURY,CTA BUS STOP,True,False,...,49.0,1.0,04B,1161801.0,1948295.0,2018,01/28/2019 04:06:33 PM,42.013796,-87.679983,"(42.013796364, -87.679982964)"
18,11529741,JB545617,2018-12-08 20:45:00,088XX S PAULINA ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,True,False,...,21.0,71.0,07,1166555.0,1846053.0,2018,01/28/2019 04:06:33 PM,41.733135,-87.665418,"(41.733135097, -87.665417802)"
19,11522868,JB536667,2018-12-01 22:30:00,022XX W DIVERSEY PKWY,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,PARKING LOT/GARAGE(NON.RESID.),True,False,...,1.0,22.0,04B,1161089.0,1918562.0,2018,01/28/2019 04:06:33 PM,41.932223,-87.683433,"(41.932222582, -87.683432779)"
20,11514795,JB525908,2018-11-22 19:04:00,060XX S BISHOP ST,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,True,True,...,16.0,67.0,26,1167697.0,1864755.0,2018,01/28/2019 04:06:33 PM,41.784432,-87.660698,"(41.784431508, -87.660698393)"
21,11509472,JB518796,2018-11-16 08:00:00,060XX S BISHOP ST,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,True,True,...,16.0,67.0,26,1167697.0,1864755.0,2018,01/28/2019 04:06:33 PM,41.784432,-87.660698,"(41.784431508, -87.660698393)"
22,11492618,JB496777,2018-10-30 17:00:00,060XX S BISHOP ST,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,True,True,...,16.0,67.0,26,1167697.0,1864755.0,2018,01/28/2019 04:06:33 PM,41.784432,-87.660698,"(41.784431508, -87.660698393)"
23,11476388,JB475307,2018-10-14 15:00:00,033XX W MADISON ST,041A,BATTERY,AGGRAVATED: HANDGUN,SIDEWALK,True,False,...,28.0,27.0,04B,1154128.0,1899819.0,2018,01/28/2019 04:06:33 PM,41.880932,-87.709515,"(41.880932047, -87.709514547)"
24,11474800,JB473149,2018-10-12 17:32:00,048XX N NAGLE AVE,0460,BATTERY,SIMPLE,STREET,True,False,...,45.0,10.0,08B,1132550.0,1931891.0,2018,01/28/2019 04:06:33 PM,41.969345,-87.788000,"(41.969344524, -87.787999685)"
25,11473488,JB471316,2018-10-06 04:00:00,047XX S CALUMET AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,3.0,38.0,08B,1179233.0,1873624.0,2018,01/28/2019 04:06:33 PM,41.808513,-87.618133,"(41.808513431, -87.618132524)"
26,11463314,JB457826,2018-09-30 14:30:00,040XX W VAN BUREN ST,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,True,True,...,28.0,26.0,26,1149436.0,1897715.0,2018,01/28/2019 04:06:33 PM,41.875251,-87.726798,"(41.875250729, -87.726797963)"
27,11290232,JB230497,2018-04-19 22:35:00,046XX N FRANCISCO AVE,0320,ROBBERY,STRONGARM - NO WEAPON,CTA PLATFORM,True,False,...,33.0,14.0,03,1156204.0,1930784.0,2018,01/28/2019 04:06:33 PM,41.965861,-87.701053,"(41.965860757, -87.701053221)"
28,11220823,JB138227,2018-01-31 19:00:00,048XX W SCHOOL ST,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,APARTMENT,True,True,...,31.0,15.0,02,1143454.0,1921501.0,2018,01/28/2019 04:06:33 PM,41.940636,-87.748166,"(41.94063601, -87.748165955)"
29,11554607,JC102267,2018-12-09 23:00:00,057XX S DAMEN AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,APARTMENT,True,True,...,15.0,67.0,02,1164006.0,1866608.0,2018,01/27/2019 04:03:13 PM,41.789595,-87.674179,"(41.789594815, -87.67417902)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51956,11192243,JB100045,2018-01-01 00:10:00,071XX W 64TH ST,0460,BATTERY,SIMPLE,APARTMENT,True,False,...,23.0,64.0,08B,1129893.0,1861263.0,2018,05/04/2018 03:51:04 PM,41.775577,-87.799385,"(41.775576711, -87.799385166)"
51957,11192241,JB100073,2018-01-01 01:05:00,051XX S CALUMET AVE,2027,NARCOTICS,POSS: CRACK,STREET,True,False,...,3.0,40.0,18,1179365.0,1871004.0,2018,05/04/2018 03:51:04 PM,41.801321,-87.617728,"(41.801320907, -87.617728391)"
51958,11192228,JB100029,2018-01-01 00:27:00,022XX S KEDZIE AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,ALLEY,True,False,...,24.0,30.0,15,1155375.0,1888899.0,2018,05/04/2018 03:51:04 PM,41.850941,-87.705229,"(41.850941431, -87.705229007)"
51959,11192225,JB100070,2018-01-01 00:52:00,039XX S ARCHER AVE,2022,NARCOTICS,POSS: COCAINE,STREET,True,False,...,12.0,58.0,18,1159000.0,1878185.0,2018,05/04/2018 03:51:04 PM,41.821467,-87.692218,"(41.821467456, -87.692217949)"
51960,23882,JB212246,2018-04-05 10:36:00,069XX S CLYDE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,5.0,43.0,01A,1191408.0,1859410.0,2018,05/03/2018 03:49:53 PM,41.769223,-87.573939,"(41.769222543, -87.573938576)"
51961,23908,JB236716,2018-04-24 21:23:00,038XX W ROOSEVELT RD,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,24.0,29.0,01A,1150993.0,1894437.0,2018,05/01/2018 03:58:00 PM,41.866225,-87.721167,"(41.866225191, -87.721167065)"
51962,23787,JB125747,2018-01-22 18:28:00,010XX E 80TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,8.0,44.0,01A,1184740.0,1852175.0,2018,04/26/2018 03:48:19 PM,41.749528,-87.598607,"(41.749527954, -87.598606502)"
51963,23778,JB120039,2018-01-18 03:45:00,066XX S EVANS AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,20.0,42.0,01A,1182361.0,1861107.0,2018,04/25/2018 03:54:41 PM,41.774094,-87.607048,"(41.774093686, -87.607047693)"
51964,23777,JB120039,2018-01-18 03:41:00,066XX S EVANS AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,20.0,42.0,01A,1182361.0,1861107.0,2018,04/25/2018 03:54:41 PM,41.774094,-87.607048,"(41.774093686, -87.607047693)"
51965,23895,JB227774,2018-04-17 19:42:00,002XX W 87TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,PARKING LOT,True,False,...,21.0,44.0,01A,1176368.0,1847206.0,2018,04/24/2018 04:08:45 PM,41.736084,-87.629434,"(41.736084484, -87.629433662)"
51966,23861,JB188232,2018-03-16 18:39:00,123XX S LOWE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,34.0,53.0,01A,1174213.0,1823101.0,2018,04/20/2018 04:05:10 PM,41.669985,-87.638042,"(41.669984891, -87.638041775)"
51967,23890,JB220614,2018-04-12 08:35:00,043XX W MADISON ST,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,True,True,...,28.0,26.0,01A,1147559.0,1899663.0,2018,04/19/2018 04:04:21 PM,41.880632,-87.733640,"(41.880632459, -87.733639652)"
51968,23873,JB196349,2018-03-23 02:42:00,004XX N STATE ST,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,True,False,...,42.0,8.0,01A,1176292.0,1903428.0,2018,04/09/2018 04:09:01 PM,41.890364,-87.628022,"(41.89036442, -87.628021535)"
51969,23874,JB196683,2018-03-23 11:29:00,001XX E 37TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,3.0,35.0,01A,1177938.0,1880167.0,2018,03/30/2018 03:53:14 PM,41.826497,-87.622684,"(41.82649745, -87.622683779)"
51970,23859,JB184667,2018-03-13 17:46:00,025XX W FITCH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HALLWAY,True,False,...,50.0,2.0,01A,1158111.0,1947358.0,2018,03/20/2018 03:52:25 PM,42.011302,-87.693586,"(42.011301687, -87.693586328)"
51971,23838,JB163448,2018-02-24 08:23:00,066XX S MINERVA AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,5.0,42.0,01A,1185025.0,1861230.0,2018,03/03/2018 03:54:43 PM,41.774369,-87.597278,"(41.774369057, -87.597278237)"
51972,23835,JB161360,2018-02-22 15:35:00,112XX S DR MARTIN LUTHER KING JR DR,0110,HOMICIDE,FIRST DEGREE MURDER,PARK PROPERTY,True,False,...,9.0,49.0,01A,1180913.0,1830483.0,2018,03/01/2018 03:54:55 PM,41.690091,-87.613295,"(41.690091209, -87.61329487)"
51973,23834,JB160133,2018-02-22 09:22:00,027XX S AVERS AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,22.0,30.0,01A,1151152.0,1885454.0,2018,03/01/2018 03:54:55 PM,41.841572,-87.720819,"(41.841571637, -87.720818596)"
51974,23817,JB101973,2018-01-12 07:00:00,033XX N MARSHFIELD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,YMCA,True,False,...,44.0,6.0,01A,1164729.0,1922247.0,2018,02/28/2018 03:56:25 PM,41.942258,-87.669951,"(41.942257928, -87.669951491)"
51975,23823,JB150650,2018-02-13 14:12:00,001XX W RANDOLPH ST,0110,HOMICIDE,FIRST DEGREE MURDER,GOVERNMENT BUILDING,True,False,...,42.0,32.0,01A,1175414.0,1901275.0,2018,02/20/2018 04:02:31 PM,41.884476,-87.631311,"(41.884476226, -87.631310613)"
51976,23822,JB149168,2018-02-12 12:00:00,015XX S KOLIN AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,24.0,29.0,01A,1147636.0,1892146.0,2018,02/19/2018 03:55:38 PM,41.860003,-87.733550,"(41.860003433, -87.733549773)"
51977,23820,JB148176,2018-02-11 13:03:00,073XX S BELL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,False,...,18.0,66.0,01A,1162674.0,1855992.0,2018,02/18/2018 03:47:38 PM,41.760491,-87.679359,"(41.760490977, -87.679359084)"
51978,23809,JB140367,2018-02-03 21:03:00,024XX W 63RD ST,0110,HOMICIDE,FIRST DEGREE MURDER,APARTMENT,True,True,...,15.0,66.0,01A,1160989.0,1862809.0,2018,02/10/2018 04:08:39 PM,41.779233,-87.685346,"(41.779232785, -87.685346466)"
51979,23805,JB139300,2018-02-02 21:51:00,086XX S CARPENTER ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,21.0,71.0,01A,1170825.0,1847590.0,2018,02/09/2018 04:07:13 PM,41.737261,-87.649730,"(41.737260844, -87.649730029)"
51980,23798,JB135745,2018-01-30 21:51:00,024XX W EASTWOOD AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,47.0,4.0,01A,1159285.0,1930760.0,2018,02/09/2018 03:44:29 PM,41.965732,-87.689726,"(41.965731951, -87.689725637)"
51981,23782,JB123082,2018-01-20 13:53:00,000XX W 69TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,CTA PROPERTY,True,False,...,6.0,69.0,01A,1177279.0,1859276.0,2018,02/04/2018 03:51:29 PM,41.769185,-87.625732,"(41.769185486, -87.625732415)"
51982,23792,JB128067,2018-01-24 14:47:00,050XX W FULLERTON AVE,0110,HOMICIDE,FIRST DEGREE MURDER,RETAIL STORE,True,False,...,31.0,19.0,01A,1142454.0,1915492.0,2018,01/31/2018 03:55:34 PM,41.924165,-87.751991,"(41.924165391, -87.751991106)"
51983,23773,JB111912,2018-01-11 05:51:00,049XX S CICERO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,GAS STATION,True,False,...,23.0,56.0,01A,1145196.0,1871375.0,2018,01/18/2018 03:58:25 PM,41.803051,-87.743030,"(41.803051264, -87.743030382)"
51984,23770,JB110156,2018-01-09 17:22:00,019XX N ALBANY AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,35.0,22.0,01A,1155202.0,1912541.0,2018,01/18/2018 03:52:54 PM,41.915821,-87.705229,"(41.915820895, -87.705228873)"
51985,23774,JB110632,2018-01-10 03:18:00,013XX N LOREL AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,37.0,25.0,01A,1140394.0,1908422.0,2018,01/17/2018 03:56:34 PM,41.904803,-87.759734,"(41.904802597, -87.75973423)"

In [164]:
data['lat'], data['long'] = data['Location'].str.split(',', 1).str

In [165]:
data.head(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,lat,long
0,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.574960,"(41.761893792, -87.574959656)",(41.761893792,-87.574959656)
1,11492004,JB495913,2018-10-29 13:00:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)",(41.776382364,-87.594556922)
2,11488952,JB491843,2018-10-27 02:00:00,070XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1190765.0,1858575.0,2018,01/30/2019 04:08:28 PM,41.766947,-87.576322,"(41.766946791, -87.57632241)",(41.766946791,-87.57632241)

In [167]:
data['lat'] = data['lat'].str.replace('(', '')

In [170]:
data['long'] = data['long'].str.replace(')', '')

In [171]:
data.head(3)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,lat,long
0,11492177,JB496165,2018-10-29 21:45:00,073XX S CHAPPEL AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1191153.0,1856737.0,2018,01/30/2019 04:08:28 PM,41.761894,-87.574960,"(41.761893792, -87.574959656)",41.761893792,41.761893792
1,11492004,JB495913,2018-10-29 13:00:00,065XX S KIMBARK AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1185761.0,1861970.0,2018,01/30/2019 04:08:28 PM,41.776382,-87.594557,"(41.776382364, -87.594556922)",41.776382364,41.776382364
2,11488952,JB491843,2018-10-27 02:00:00,070XX S JEFFERY BLVD,0820,THEFT,$500 AND UNDER,STREET,False,False,...,06,1190765.0,1858575.0,2018,01/30/2019 04:08:28 PM,41.766947,-87.576322,"(41.766946791, -87.57632241)",41.766946791,41.766946791

In [175]:
data.drop(['lat' , 'long'], inplace=True, axis=1)

### Grouping the data frame based on Primary Type

In [177]:
group_by = data.groupby(['Primary Type']).count()

,ID,Case Number,Date,Block,IUCR,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
Primary Type,,,,,,,,,,,,,,,,,,,,,
ARSON,372,372,372,372,372,372,372,372,372,372,...,372,372,372,372,372,372,372,372,372,372
ASSAULT,20344,20344,20344,20344,20344,20344,20344,20344,20344,20344,...,20344,20344,20344,20344,20344,20344,20344,20344,20344,20344
BATTERY,49733,49733,49733,49733,49733,49733,49733,49733,49733,49733,...,49733,49733,49733,49733,49733,49733,49733,49733,49733,49733
BURGLARY,11687,11687,11687,11687,11687,11687,11687,11687,11687,11687,...,11687,11687,11687,11687,11687,11687,11687,11687,11687,11687
CONCEALED CARRY LICENSE VIOLATION,148,148,148,148,148,148,148,148,148,148,...,148,148,148,148,148,148,148,148,148,148
CRIM SEXUAL ASSAULT,1583,1583,1583,1583,1583,1583,1583,1583,1583,1583,...,1583,1583,1583,1583,1583,1583,1583,1583,1583,1583
CRIMINAL DAMAGE,27705,27705,27705,27705,27705,27705,27705,27705,27705,27705,...,27705,27705,27705,27705,27705,27705,27705,27705,27705,27705
CRIMINAL TRESPASS,6880,6880,6880,6880,6880,6880,6880,6880,6880,6880,...,6880,6880,6880,6880,6880,6880,6880,6880,6880,6880
DECEPTIVE PRACTICE,17247,17247,17247,17247,17247,17247,17247,17247,17247,17247,...,17247,17247,17247,17247,17247,17247,17247,17247,17247,17247
GAMBLING,201,201,201,201,201,201,201,201,201,201,...,201,201,201,201,201,201,201,201,201,201
HOMICIDE,584,584,584,584,584,584,584,584,584,584,...,584,584,584,584,584,584,584,584,584,584
HUMAN TRAFFICKING,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
INTERFERENCE WITH PUBLIC OFFICER,1305,1305,1305,1305,1305,1305,1305,1305,1305,1305,...,1305,1305,1305,1305,1305,1305,1305,1305,1305,1305
INTIMIDATION,166,166,166,166,166,166,166,166,166,166,...,166,166,166,166,166,166,166,166,166,166
KIDNAPPING,172,172,172,172,172,172,172,172,172,172,...,172,172,172,172,172,172,172,172,172,172
LIQUOR LAW VIOLATION,265,265,265,265,265,265,265,265,265,265,...,265,265,265,265,265,265,265,265,265,265
MOTOR VEHICLE THEFT,9981,9981,9981,9981,9981,9981,9981,9981,9981,9981,...,9981,9981,9981,9981,9981,9981,9981,9981,9981,9981
NARCOTICS,12798,12798,12798,12798,12798,12798,12798,12798,12798,12798,...,12798,12798,12798,12798,12798,12798,12798,12798,12798,12798
NON-CRIMINAL,37,37,37,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
NON-CRIMINAL (SUBJECT SPECIFIED),3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
OBSCENITY,86,86,86,86,86,86,86,86,86,86,...,86,86,86,86,86,86,86,86,86,86
OFFENSE INVOLVING CHILDREN,2203,2203,2203,2203,2203,2203,2203,2203,2203,2203,...,2203,2203,2203,2203,2203,2203,2203,2203,2203,2203
OTHER NARCOTIC VIOLATION,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
OTHER OFFENSE,16982,16982,16982,16982,16982,16982,16982,16982,16982,16982,...,16982,16982,16982,16982,16982,16982,16982,16982,16982,16982
PROSTITUTION,717,717,717,717,717,717,717,717,717,717,...,717,717,717,717,717,717,717,717,717,717
PUBLIC INDECENCY,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
PUBLIC PEACE VIOLATION,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362,...,1362,1362,1362,1362,1362,1362,1362,1362,1362,1362
ROBBERY,9685,9685,9685,9685,9685,9685,9685,9685,9685,9685,...,9685,9685,9685,9685,9685,9685,9685,9685,9685,9685
SEX OFFENSE,1053,1053,1053,1053,1053,1053,1053,1053,1053,1053,...,1053,1053,1053,1053,1053,1053,1053,1053,1053,1053
STALKING,202,202,202,202,202,202,202,202,202,202,...,202,202,202,202,202,202,202,202,202,202
THEFT,64039,64039,64039,64039,64039,64039,64039,64039,64039,64039,...,64039,64039,64039,64039,64039,64039,64039,64039,64039,64039
WEAPONS VIOLATION,5443,5443,5443,5443,5443,5443,5443,5443,5443,5443,...,5443,5443,5443,5443,5443,5443,5443,5443,5443,5443

In [179]:
sorted = data.sort_values(by=['Date'], ascending=True).reset_index()

In [180]:
sorted.head(4)

,index,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,250284,11212228,JB127156,2018-01-01,109XX S HALSTED ST,0810,THEFT,OVER $500,NURSING HOME/RETIREMENT HOME,False,...,34.0,49.0,06,1172930.0,1832289.0,2018,05/04/2018 03:51:04 PM,41.695227,-87.642468,"(41.69522655, -87.642467755)"
1,192302,11294302,JB235992,2018-01-01,003XX N KEDZIE AVE,0810,THEFT,OVER $500,STREET,False,...,28.0,27.0,06,1154989.0,1901961.0,2018,05/04/2018 03:51:04 PM,41.886793,-87.706296,"(41.886792691, -87.706295532)"
2,137254,11372246,JB339225,2018-01-01,004XX N RIDGEWAY AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,27.0,23.0,11,1151309.0,1902739.0,2018,07/11/2018 03:52:51 PM,41.889001,-87.719789,"(41.889000598, -87.719789123)"
3,218548,11257074,JB184108,2018-01-01,051XX W SCHUBERT AVE,0266,CRIM SEXUAL ASSAULT,PREDATORY,RESIDENCE,False,...,31.0,19.0,02,1141572.0,1917468.0,2018,05/04/2018 03:51:04 PM,41.929604,-87.755183,"(41.929604102, -87.75518302)"